Crud fix individual use
EduardoGiacomini/mafcust-frontend pull request #14
Opened 2022-05-24 01:00 UTC by brunomond

### Overview
Added: Feature to connect IndividualUse on Patients
Modified: Logical delete on IndividualUse

### Pull request type
- [ ] Bug fixes;
- [x] New feature;
- [ ] Refactoring;
- [ ] Documentation;
- [ ] Other: __________________

Closes: #20

2022-05-24 22:39 UTC, SantiagoMateus approved these changes

2022-05-24 23:35 UTC, EduardoGiacomini requested changes
Show.

Duas coisas não estão funcionando bem:
1. Ao editar um custo individual a quantidade não vem pré-selecionada.
2. Não consigo adicionar exames ao paciente.

2022-05-26 00:03 UTC, EduardoGiacomini requested changes
As vezes não consigo atualizar um custo individual anexado ao paciente... ele acaba atualizando somente um dos custos independente de qual custo eu selecionar. Outras vezes dá o erro `user not allowed`.

Estou recebendo alguns erros ao tentar excluir o custo individual. Além disso, o botão cancelar não está fechando o modal.

2022-06-01 20:42 UTC, EduardoGiacomini approved these changes
I did some tests and it is ok for me. Do you have any task to do in this branch? Can we merge?
@brunomond

2022-06-01 23:04 UTC, merged